language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm 
before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev --no-interaction
    - mysql -e 'create database sf_unit;'
    - mysql -e 'use sf_unit;'
    - mysql -e 'source tests/db_desc_sf_unit.sql;'
    - echo "<?php return array('db' => array('type' => 'mysql', 'dbname' => 'sf_unit', 'username' => 'root', 'password' => '', 'host' => '127.0.0.1', 'port' => '3306', 'driver_options' => array()));" > tests/config.php

script:
  - mkdir -p build/logs
  - mkdir -p build/coverage
  - vendor/bin/phpunit -v --coverage-clover build/logs/clover.xml 

after_script:
  - php vendor/bin/coveralls  -v

notifications:
    email:
        - swansoft_team@groups.163.com
